#!/usr/bin/env python3
"""
gen_25tile_top.py
Generate lobsterpawn_25tile_top.v — 25 noc_adapter instances wired to all
25 local ports of the NoD 5x5 mesh.
"""

N = 5

def port_name(x, y):
    return f"X{x}_Y{y}"

lines = []
lines.append('// lobsterpawn_25tile_top.v  (auto-generated by gen_25tile_top.py)')
lines.append('// 25 noc_adapter instances, one per NoD local port.')
lines.append('`include "param.vh"')
lines.append('')
lines.append('module lobsterpawn_25tile_top (')
lines.append('    input wire clk,')
lines.append('    input wire rst')
lines.append(');')
lines.append('')

# Wire declarations for all 25 ports
for x in range(N):
    for y in range(N):
        p = port_name(x, y)
        lines.append(f'    wire [`DATA_WIDTH-1:0] tx_{p}, rx_{p};')
        lines.append(f'    wire                   tv_{p}, tr_{p}, rv_{p}, rr_{p};')
lines.append('')

# noc_adapter instantiations — bus tied to zero (stimulus comes from testbench)
# We expose flat arrays via generate — instead use one instance per node
lines.append('    // noc_adapter instances (bus inputs tied off; testbench drives via force)')
for x in range(N):
    for y in range(N):
        p = port_name(x, y)
        idx = x * N + y
        lines.append(f'    // Tile {idx} at ({x},{y})')
        lines.append(f'    noc_adapter #(.NODE_X({x}), .NODE_Y({y})) u_adap_{p} (')
        lines.append(f'        .clk(clk), .rstn(~rst),')
        lines.append(f'        .noc_addr(32\'b0), .noc_wdata(32\'b0),')
        lines.append(f'        .noc_rw(1\'b0), .noc_we(1\'b0),')
        lines.append(f'        .noc_rdata(), .noc_ready(),')
        lines.append(f'        .nod_tx_data(tx_{p}), .nod_tx_valid(tv_{p}), .nod_tx_ready(tr_{p}),')
        lines.append(f'        .nod_rx_data(rx_{p}), .nod_rx_valid(rv_{p}), .nod_rx_ready(rr_{p})')
        lines.append(f'    );')
        lines.append('')

# NoD instantiation
lines.append('    NoD #(.NODID(0)) u_nod (')
lines.append('        .CDCLK(clk), .CDRESETn(~rst),')
for x in range(N):
    for y in range(N):
        p = port_name(x, y)
        comma = '' if (x == N-1 and y == N-1) else ','
        lines.append(f'        .CDIDATA_{p}(tx_{p}), .CDIVALID_{p}(tv_{p}), .CDIREADY_{p}(tr_{p}),')
        lines.append(f'        .CDODATA_{p}(rx_{p}), .CDOVALID_{p}(rv_{p}), .CDOREADY_{p}(rr_{p}){comma}')
lines.append('    );')
lines.append('')
lines.append('endmodule')

out = '\n'.join(lines)
path = 'rtl/top/lobsterpawn_25tile_top.v'
with open(path, 'w') as f:
    f.write(out)
print(f'Written: {path}  ({len(lines)} lines)')
