-d C:\Users\zcq\OneDrive\UoG_challenge_course\TangPrimer-20K-example-main\TangPrimer-20K-example-main\HDMI\impl\gwsynthesis\dk_video.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\zcq\OneDrive\UoG_challenge_course\TangPrimer-20K-example-main\TangPrimer-20K-example-main\HDMI\src\dk_video.cst
-cfg C:\Users\zcq\OneDrive\UoG_challenge_course\TangPrimer-20K-example-main\TangPrimer-20K-example-main\HDMI\impl\pnr\device.cfg
-sdc C:\Users\zcq\OneDrive\UoG_challenge_course\TangPrimer-20K-example-main\TangPrimer-20K-example-main\HDMI\src\dk_video.sdc
-bit
-tr
-ph
-timing
-route_maxfan 23
